const express = require('express');
const { authenticateToken } = require("../middleware/auth");
const StationController = require('../controllers/stationController.js');
const router = express.Router();
router.post('/', authenticateToken, StationController.createStation);
router.get('/', authenticateToken, StationController.getStations);
router.get('/:id', authenticateToken, StationController.getStationById);
router.put('/:id', authenticateToken, StationController.updateStation);
router.delete('/:id', authenticateToken, StationController.deleteStation);
module.exports = router;
